# action.yml
name: 'Hello CMSSW'
description: 'Inspect a file and return something'
inputs:
  file-name:  # id of input
    description: 'File name'
    required: true
    default: 'root://eospublic.cern.ch//eos/opendata/cms/hidata/HIRun2011/HIHighPt/RECO/15Apr2013-v1/110000/10EF1D2D-77B4-E211-A652-003048F1C494.root'
  CMSSW_VERSION:  # id of input
    description: 'CMSSW version'
    required: true
    default: 'CMSSW_4_2_8'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  another_output: # id of output
    description: 'Another output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-name }}
    - ${{ inputs.CMSSW_VERSION }}
